name: Deploy to Azure Workflow

on: 
  push:
    branches:
    - master
    path: 
      - arm/*

jobs:
  deploy: 
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - name: Git - Get Sources
      uses: actions/checkout@master

    - name: Azure - Login
      uses: Azure/github-actions/login@master
      env: 
        AZURE_SUBSCRIPTION: MVP Azure PASS
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}  

    - name: Explore workspace
      run: ls -l

    - name: Azure - Deploy ARM Template
      uses: Azure/github-actions/arm@master
      env:
        AZURE_RESOURCE_GROUP: github-actions
        AZURE_TEMPLATE_LOCATION: ./arm/sample-arm.deploy.json
        AZURE_TEMPLATE_PARAM_LOCATION: ./arm/sample-arm.deploy.parameters.json
