name: CI

on: 
  push:
    branches:
    - master

jobs:
  login: 
    name: Azure Login
    steps:
    - uses: Azure/github-actions/login@master
      env: 
        AZURE_SUBSCRIPTION: MVP Azure PASS
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
  
  deploy:
    name: "Deploy to Azure"
    steps:
    - uses: Azure/github-actions/arm@master
      env:
        AZURE_RESOURCE_GROUP: github-actions
        AZURE_TEMPLATE_LOCATION: ./sample-arm.deploy.json
      needs: login
