name: Deploy to Azure Workflow

on: 
  push:
    branches:
    - master

jobs:
  deploy: 
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - name: Git - Get Sources
      uses: actions/checkout@master

    - name: Azure - Login
      uses: Azure/github-actions/login@master
      env: 
        AZURE_SUBSCRIPTION: MVP Azure PASS
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}  

    - name: Azure - Deploy ARM Template - Subscription Level without parameters
      uses: wilfriedwoivre/github-actions/Azure/arm@dev
      env:
        SCOPE: SUBSCRIPTION
        AZURE_TEMPLATE_LOCATION: arm-deployment-sub.json

    - name: Azure - Deploy ARM Template - Subscription Level with parameters
      uses: wilfriedwoivre/github-actions/Azure/arm@dev
      env:
        SCOPE: SUBSCRIPTION
        AZURE_TEMPLATE_LOCATION: arm-deployment-sub.json
        AZURE_TEMPLATE_PARAM_LOCATION: arm-deployment-sub.parameters.json

    - name: Azure - Deploy ARM Template - Resource Group Level without parameters
      uses: wilfriedwoivre/github-actions/Azure/arm@dev
      env:
        AZURE_RESOURCE_GROUP: test-github-action-rg
        AZURE_TEMPLATE_LOCATION: arm-deployment-rg.json

    - name: Azure - Deploy ARM Template - Resource Group Level with parameters
      uses: wilfriedwoivre/github-actions/Azure/arm@dev
      env:
        AZURE_RESOURCE_GROUP: test-github-action-rg
        AZURE_TEMPLATE_LOCATION: arm-deployment-rg.json
        AZURE_TEMPLATE_PARAM_LOCATION: arm-deployment-rg.parameters.json
