name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    
    - name: "Azure Login"
      uses: "Azure/github-actions/login@master"
      env: 
        AZURE_SUBSCRIPTION: "MVP Azure PASS"
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
