name: CI

on: 
  push:
    path:
    - '*.deploy.json'

jobs:
  action "Azure Login":
    uses: "Azure/github-actions/login@master"
    env:
    - AZURE_SUBSCRIPTION = "Subscription Name"
    
    secrets: ["AZURE_SERVICE_APP_ID", "AZURE_SERVICE_PASSWORD", "AZURE_SERVICE_TENANT"]
