name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    
    - uses: "Azure/github-actions/login@master"
      with: 
        AZURE_SUBSCRIPTION: "MVP Azure PASS"
